// OneSignal Service Worker — DO NOT EDIT this file's location.
// It MUST live at the site root (e.g. https://your-domain/OneSignalSDKWorker.js).
importScripts('https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.sw.js');
